-- Script para inicializar la base de datos

-- GENEROS (5)
INSERT INTO GENEROS(NOMBRE) VALUES ('Accion');
INSERT INTO GENEROS(NOMBRE) VALUES ('Aventura');
INSERT INTO GENEROS(NOMBRE) VALUES ('Comedia');
INSERT INTO GENEROS(NOMBRE) VALUES ('Drama');
INSERT INTO GENEROS(NOMBRE) VALUES ('Terror');

-- ACTORES (5)
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES ('Tom Cruise', 'https://image.gala.de/20511760/t/vk/v22/w1440/r1/-/tom-cruise-ge--6411731-.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES ('Brad Pitt', 'https://es.web.img3.acsta.net/pictures/19/05/22/10/42/3773139.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES ('Leonardo DiCaprio', 'https://www.elle.pl/uploads/media/default/0003/28/piec-twarzy-leonardo-dicaprio-tych-najpiekniejszych.jpeg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES ('Robert Downey Jr.', 'https://daman.co.id/daman.co.id/wp-content/uploads/2019/10/Robert-Downey-Jr-Glasses-1-1024x1024.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES ('Will Smith', 'https://www.cheatsheet.com/wp-content/uploads/2020/07/Will-Smith-3-2-scaled.jpg');

-- PELICULAS (20)
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Misión Imposible', 1, '1996-05-22');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Entrevista con el vampiro', 2, '1994-11-11');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El club de la pelea', 3, '1999-10-15');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Titanic', 4, '1997-12-19');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Django sin cadenas', 5, '2012-12-25');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El lobo de Wall Street', 3, '2013-12-25');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Avengers: Endgame', 1, '2019-04-26');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Avengers: Infinity War', 1, '2018-04-27');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Avengers: Age of Ultron', 1, '2015-05-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Black Panther', 1, '2018-02-16');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Captain America: Civil War', 1, '2016-05-06');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Captain America: The Winter Soldier', 1, '2014-04-04');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Doctor Strange', 1, '2016-11-04');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Guardians of the Galaxy', 1, '2014-08-01');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Eternals', 1, '2021-11-05');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El rey león', 1, '2019-07-19');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Toy Story 4', 1, '2019-06-21');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Frozen II', 1, '2019-11-22');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Star Wars: The Rise of Skywalker', 1, '2019-12-20');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El viaje de Chihiro', 1, '2001-07-27');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El castillo ambulante', 1, '2004-09-10');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El increíble castillo vagabundo', 1, '2004-09-10');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Mi vecino Totoro', 1, '1988-04-16');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('La princesa Mononoke', 1, '1997-10-29');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Fargo', 1, '1996-04-05');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El gran Lebowski', 1, '1998-03-06');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El señor de los anillos: La comunidad del anillo', 1, '2001-12-19');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Forrest Gump', 1, '1994-07-06');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El caballero oscuro', 1, '2008-07-18');